# Use a Python base image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY app_challenge.py .
COPY example_payloads/ example_payloads/

# Expose the port on which the Flask application runs
EXPOSE 8888

# Command to run the application
CMD ["python", "app_challenge.py"]