version: '3.8'

services:
  app_no_co2:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    restart: always

  app_with_co2:
    build:
      context: .
      dockerfile: Dockerfile.app_challenge
    ports:
      - "8889:8888" # Map to a different port to avoid conflicts
    environment:
      - CO2_EMISSION_FACTOR=0.3 # Pass the CO2 emission factor
    volumes:
      - .:/app
    restart: always